name: Documentation

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade tox
        tox --notest -e narrativedocs,apidocs

    - name: Check the narrative documentation
      run: |
        tox -q -e narrativedocs

    - name: Check the API documentation
      run: |
        tox -q -e apidocs
